local palettes = {
  escuro = {
    bg = "#17181b",
    surface = "#1e2024",
    code = "#1e2024",
    fg = "#cfcac2",
    muted = "#84807a",
    rule = "#2c2f34",
    accent = "#c59c6d",
    red = "#eb8278",
    orange = "#cf957b",
    yellow = "#d9bb5c",
    green = "#85b286",
    teal = "#63b5b4",
    blue = "#7ea9d5",
    purple = "#b098cd",
    fn = "#7ea9d5",
    const = "#b098cd",
    special = "#d2918b",
  },
  claro = {
    bg = "#faf9f7",
    surface = "#f3f1ed",
    code = "#f0eee9",
    fg = "#1c1b19",
    muted = "#6f6a63",
    rule = "#e3dfd8",
    accent = "#32618e",
    red = "#a04038",
    orange = "#874c30",
    yellow = "#886100",
    green = "#3a6b3d",
    teal = "#006d6d",
    blue = "#32618e",
    purple = "#695086",
    fn = "#695086",
    const = "#874c30",
    special = "#7b5518",
  },
  sepia = {
    bg = "#e8e6dd",
    surface = "#f1f0e9",
    code = "#dedcd2",
    fg = "#252525",
    muted = "#6f6f69",
    rule = "#d3d1c5",
    accent = "#884b35",
    red = "#a04038",
    orange = "#81462b",
    yellow = "#825b00",
    green = "#356537",
    teal = "#006768",
    blue = "#2d5b88",
    purple = "#644a80",
    fn = "#2d5b88",
    const = "#644a80",
    special = "#755010",
  },
}

local light = vim.o.background == "light"
local p = palettes[light and (vim.g.camargo_light or "sepia") or "escuro"]

local function blend(color, base, alpha)
  local function channel(c, i)
    return tonumber(c:sub(i, i + 1), 16)
  end
  local mixed = {}
  for i = 2, 6, 2 do
    table.insert(mixed, math.floor(channel(color, i) * alpha + channel(base, i) * (1 - alpha) + 0.5))
  end
  return string.format("#%02x%02x%02x", unpack(mixed))
end

local border = blend(p.muted, p.bg, 0.45)
local dim = blend(p.muted, p.bg, 0.6)

vim.cmd("highlight clear")
vim.g.colors_name = "camargo"

local hl = {
  Normal = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.surface },
  FloatBorder = { fg = border, bg = p.surface },
  FloatTitle = { fg = p.accent, bg = p.surface, bold = true },
  Pmenu = { fg = p.fg, bg = p.surface },
  PmenuSel = { bg = p.rule, bold = true },
  PmenuKind = { fg = p.muted, bg = p.surface },
  PmenuExtra = { fg = p.muted, bg = p.surface },
  PmenuSbar = { bg = p.surface },
  PmenuThumb = { bg = p.rule },
  WildMenu = { link = "PmenuSel" },

  Cursor = { fg = p.bg, bg = p.accent },
  CursorLine = { bg = p.code },
  CursorColumn = { bg = p.code },
  ColorColumn = { bg = p.code },
  CursorLineNr = { fg = p.accent, bold = true },
  LineNr = { fg = dim },
  SignColumn = { fg = p.muted },
  FoldColumn = { fg = dim },
  Folded = { fg = p.muted, bg = p.code },
  WinSeparator = { fg = p.rule },
  StatusLine = { fg = p.muted, bg = p.surface },
  StatusLineNC = { fg = dim, bg = p.bg },
  TabLine = { fg = p.muted, bg = p.surface },
  TabLineFill = { bg = p.bg },
  TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
  WinBar = { fg = p.muted },
  WinBarNC = { fg = dim },

  Visual = { bg = blend(p.accent, p.bg, 0.22) },
  Search = { bg = blend(p.yellow, p.bg, 0.3) },
  CurSearch = { fg = p.bg, bg = p.accent, bold = true },
  IncSearch = { fg = p.bg, bg = p.accent, bold = true },
  Substitute = { fg = p.bg, bg = p.red },
  MatchParen = { fg = p.accent, bold = true, underline = true },
  NonText = { fg = blend(p.muted, p.bg, 0.4) },
  Whitespace = { link = "NonText" },
  SpecialKey = { link = "NonText" },
  EndOfBuffer = { fg = p.bg },
  Conceal = { fg = p.muted },
  Directory = { fg = p.accent },
  Title = { fg = p.accent, bold = true },
  QuickFixLine = { bg = p.code, bold = true },

  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.yellow },
  MoreMsg = { fg = p.green },
  Question = { fg = p.blue },
  ModeMsg = { fg = p.muted, bold = true },

  SpellBad = { undercurl = true, sp = p.red },
  SpellCap = { undercurl = true, sp = p.yellow },
  SpellLocal = { undercurl = true, sp = p.teal },
  SpellRare = { undercurl = true, sp = p.purple },

  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },
  DiffAdd = { bg = blend(p.green, p.bg, 0.18) },
  DiffChange = { bg = blend(p.blue, p.bg, 0.14) },
  DiffText = { bg = blend(p.blue, p.bg, 0.32) },
  DiffDelete = { fg = blend(p.red, p.bg, 0.6), bg = blend(p.red, p.bg, 0.14) },

  Comment = { fg = p.muted, italic = true },
  Constant = { fg = p.const },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.const },
  Boolean = { fg = p.const },
  Identifier = { fg = p.fg },
  Function = { fg = p.fn },
  Statement = { fg = p.accent },
  Keyword = { fg = p.accent },
  Operator = { fg = blend(p.fg, p.muted, 0.5) },
  PreProc = { fg = p.special },
  Type = { fg = p.teal },
  Special = { fg = p.special },
  Delimiter = { fg = p.muted },
  Underlined = { underline = true },
  Todo = { fg = p.bg, bg = p.accent, bold = true },
  Error = { fg = p.red },

  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.special, italic = true },
  ["@variable.parameter"] = { fg = p.fg },
  ["@variable.member"] = { fg = p.fg },
  ["@property"] = { fg = p.fg },
  ["@constant"] = { fg = p.const },
  ["@constant.builtin"] = { fg = p.const },
  ["@module"] = { fg = p.teal },
  ["@label"] = { fg = p.accent },
  ["@string"] = { fg = p.green },
  ["@string.escape"] = { fg = p.special },
  ["@string.regexp"] = { fg = p.teal },
  ["@string.special.url"] = { fg = p.blue, underline = true },
  ["@number"] = { fg = p.const },
  ["@boolean"] = { fg = p.const },
  ["@type"] = { fg = p.teal },
  ["@type.builtin"] = { fg = p.teal, italic = true },
  ["@attribute"] = { fg = p.special },
  ["@function"] = { fg = p.fn },
  ["@function.builtin"] = { fg = p.fn, italic = true },
  ["@constructor"] = { fg = p.teal },
  ["@keyword"] = { fg = p.accent },
  ["@operator"] = { link = "Operator" },
  ["@punctuation"] = { fg = p.muted },
  ["@punctuation.special"] = { fg = p.special },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { fg = p.accent, bold = true },
  ["@comment.note"] = { fg = p.blue, bold = true },
  ["@comment.warning"] = { fg = p.yellow, bold = true },
  ["@comment.error"] = { fg = p.red, bold = true },
  ["@tag"] = { fg = p.accent },
  ["@tag.attribute"] = { fg = p.teal },
  ["@tag.delimiter"] = { fg = p.muted },

  ["@markup.heading"] = { fg = p.accent, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.quote"] = { fg = p.muted, italic = true },
  ["@markup.link"] = { fg = p.accent },
  ["@markup.link.label"] = { fg = p.accent },
  ["@markup.link.url"] = { fg = p.muted, underline = true },
  ["@markup.raw"] = { fg = p.special },
  ["@markup.raw.block"] = { fg = p.fg },
  ["@markup.list"] = { fg = p.accent },
  ["@markup.list.checked"] = { fg = p.green },
  ["@markup.list.unchecked"] = { fg = p.muted },
  ["@markup.math"] = { fg = p.teal },
  ["@diff.plus"] = { link = "Added" },
  ["@diff.minus"] = { link = "Removed" },
  ["@diff.delta"] = { link = "Changed" },

  LspReferenceText = { bg = p.rule },
  LspReferenceRead = { bg = p.rule },
  LspReferenceWrite = { bg = p.rule, underline = true },
  LspInlayHint = { fg = dim, italic = true },
  LspCodeLens = { fg = p.muted },
  LspSignatureActiveParameter = { fg = p.accent, bold = true },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.teal },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.teal },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.green },
  DiagnosticVirtualTextError = { fg = p.red, bg = blend(p.red, p.bg, 0.1) },
  DiagnosticVirtualTextWarn = { fg = p.yellow, bg = blend(p.yellow, p.bg, 0.1) },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = blend(p.blue, p.bg, 0.1) },
  DiagnosticVirtualTextHint = { fg = p.teal, bg = blend(p.teal, p.bg, 0.1) },
  DiagnosticVirtualTextOk = { fg = p.green, bg = blend(p.green, p.bg, 0.1) },

  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },

  SnacksIndent = { fg = p.rule },
  SnacksIndentScope = { fg = p.muted },
  SnacksPickerMatch = { fg = p.accent, bold = true },
  SnacksPickerDir = { fg = p.muted },
  SnacksDashboardHeader = { fg = p.accent },
  SnacksDashboardIcon = { fg = p.muted },
  SnacksDashboardKey = { fg = p.accent },
  SnacksDashboardDesc = { fg = p.fg },
  SnacksDashboardFooter = { fg = p.muted, italic = true },
  SnacksDashboardSpecial = { fg = p.special },

  BlinkCmpLabelMatch = { fg = p.accent, bold = true },
  BlinkCmpKind = { fg = p.muted },
  BlinkCmpGhostText = { fg = p.muted, italic = true },

  WhichKey = { fg = p.accent },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.muted },

  FlashBackdrop = { fg = p.muted },
  FlashMatch = { bg = p.rule },
  FlashCurrent = { fg = p.bg, bg = p.yellow },
  FlashLabel = { fg = p.bg, bg = p.accent, bold = true },

  NoiceCmdlineIcon = { fg = p.accent },
  NoiceCmdlinePopupBorder = { fg = border },
  NoiceCmdlinePopupTitle = { fg = p.accent, bold = true },

  MiniIconsAzure = { fg = p.blue },
  MiniIconsBlue = { fg = p.blue },
  MiniIconsCyan = { fg = p.teal },
  MiniIconsGreen = { fg = p.green },
  MiniIconsGrey = { fg = p.muted },
  MiniIconsOrange = { fg = p.orange },
  MiniIconsPurple = { fg = p.purple },
  MiniIconsRed = { fg = p.red },
  MiniIconsYellow = { fg = p.yellow },

  RenderMarkdownCode = { bg = p.code },
  RenderMarkdownCodeInline = { bg = p.code },
  RenderMarkdownQuote = { fg = p.muted },
  RenderMarkdownBullet = { fg = p.accent },
  RenderMarkdownH1Bg = { bg = p.code },
  RenderMarkdownH2Bg = { bg = p.code },
  RenderMarkdownH3Bg = { bg = p.code },
  RenderMarkdownH4Bg = { bg = p.code },
  RenderMarkdownH5Bg = { bg = p.code },
  RenderMarkdownH6Bg = { bg = p.code },

  MasonHeader = { fg = p.bg, bg = p.accent, bold = true },
  MasonHighlight = { fg = p.accent },
  MasonHighlightBlock = { fg = p.bg, bg = p.accent },
  MasonHighlightBlockBold = { fg = p.bg, bg = p.accent, bold = true },
  MasonMuted = { fg = p.muted },
  MasonMutedBlock = { fg = p.fg, bg = p.rule },
}

for name, spec in pairs(hl) do
  vim.api.nvim_set_hl(0, name, spec)
end

local black, white = p.rule, p.fg
if light then
  black, white = p.fg, p.rule
end
for i, color in ipairs({ black, p.red, p.green, p.yellow, p.blue, p.purple, p.teal, white }) do
  vim.g["terminal_color_" .. (i - 1)] = color
  vim.g["terminal_color_" .. (i + 7)] = color
end
vim.g.terminal_color_8 = p.muted
